<?php
/**
 * @file
 * Hook functions for the asusf_installer_forms module.
 */

/**
 * Implements hook_theme().
 */
function asusf_installer_forms_theme($existing, $type, $theme, $path) {
  return [
    'multi_step_wrapper' => [
      'base hook' => 'container',
      'render element' => 'element',
      'template' => 'form--multi-step-ajax-form',
      'path' => \Drupal::service('extension.list.module')->getPath('asusf_installer_forms') . '/templates',
    ],
  ];
}
